In [1]:
import numpy as np
import pandas as pd

In [89]:
data = pd.read_csv('Clean_Car_data' ,index_col=0)

In [90]:
data

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing,Hyundai,2007-01-01,80000,45000,Petrol
1,Mahindra Jeep CL550,Mahindra,2006-01-01,425000,40,Diesel
3,Hyundai Grand i10,Hyundai,2014-01-01,325000,28000,Petrol
4,Ford EcoSport Titanium,Ford,2014-01-01,575000,36000,Diesel
6,Ford Figo,Ford,2012-01-01,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz,Maruti,2011-01-01,270000,50000,Petrol
885,Tata Indica V2,Tata,2009-01-01,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009-01-01,300000,132000,Petrol
888,Tata Zest XM,Tata,2018-01-01,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013-01-01,390000,40000,Diesel

In [91]:
data = data[data['Price']<5000000]
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 723 entries, 0 to 889
Data columns (total 6 columns):
name          723 non-null object
company       723 non-null object
year          723 non-null object
Price         723 non-null int64
kms_driven    723 non-null int64
fuel_type     723 non-null object
dtypes: int64(2), object(4)
memory usage: 39.5+ KB

In [92]:
data.describe()

              Price     kms_driven
count  7.230000e+02     723.000000
mean   3.920462e+05   46793.820194
std    3.742673e+05   34599.288028
min    3.000000e+04       0.000000
25%    1.650000e+05   27000.000000
50%    2.900000e+05   42000.000000
75%    4.899990e+05   59000.000000
max    3.100000e+06  400000.000000

In [129]:
data.year = data.year.str.replace('-', '').astype('int64')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [130]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 723 entries, 0 to 889
Data columns (total 6 columns):
name          723 non-null object
company       723 non-null object
year          723 non-null int64
Price         723 non-null int64
kms_driven    723 non-null int64
fuel_type     723 non-null object
dtypes: int64(3), object(3)
memory usage: 39.5+ KB

In [131]:
X =  data[['name','company','year', 'kms_driven', 'fuel_type' ]]
X

                       name   company      year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  20070101       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  20060101          40    Diesel
3         Hyundai Grand i10   Hyundai  20140101       28000    Petrol
4    Ford EcoSport Titanium      Ford  20140101       36000    Diesel
6                 Ford Figo      Ford  20120101       41000    Diesel
..                      ...       ...       ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  20110101       50000    Petrol
885          Tata Indica V2      Tata  20090101       30000    Diesel
886    Toyota Corolla Altis    Toyota  20090101      132000    Petrol
888            Tata Zest XM      Tata  20180101       27000    Diesel
889      Mahindra Quanto C8  Mahindra  20130101       40000    Diesel

[723 rows x 5 columns]

In [132]:
y  = data.Price
y

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
883    270000
885    110000
886    300000
888    260000
889    390000
Name: Price, Length: 723, dtype: int64

In [214]:
y[886]

300000

# Apply Training & Testing

In [182]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state = 0)

In [183]:
from sklearn.linear_model import LinearRegression

In [184]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer 
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [185]:
oho = OneHotEncoder()
oho.fit(X[['name','company','fuel_type']])

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

# creating a column transformer  to transform categorical columns

In [186]:
column_tansformer  = make_column_transformer((OneHotEncoder(categories = oho.categories_),['name','company','fuel_type']),
                                             remainder = 'passthrough')

# Make a Model

In [187]:
lr = LinearRegression()

# Make a Pipeline

In [188]:
pipe = make_pipeline(column_tansformer,lr)

# Fitting the Model

In [189]:
pipe.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categorical_features=None,
                                                                categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'B...
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                n_values=None,
                                                                sparse=True),
                                                  ['name', 'company',
                                                   'fuel_type'])],
                                   verbose=False)),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [190]:
y_pred= pipe.predict(X_test)

In [191]:
pd.DataFrame({'y_train':y_test, 'y_pred':y_pred})

     y_train         y_pred
7     190000  155525.100790
885   110000  159864.717769
28     95000   47237.271451
86   1200000  612705.644265
322   444999  425874.249497
..       ...            ...
679   360000  450587.770185
775   115000  225130.524100
633    60000  368029.802256
40    489999  505504.861424
248   535000  557121.620550

[145 rows x 2 columns]

In [192]:
r2_score(y_test,y_pred)

0.6685832463818866

In [193]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,y_pred)

35931430265.47289

In [194]:
y_pred= pipe.predict(X_train)

In [195]:
pd.DataFrame({'y_train':y_train, 'y_pred':y_pred})

     y_train         y_pred
270   499999  498250.544209
708    70000   55414.319646
402    65000  155532.450868
72    448999  520696.440557
415   270000  200752.838868
..       ...            ...
151   244999  245220.406719
523   278000  266397.101569
227   519000  716279.772218
505   135000  166674.220601
70    110000  111763.434266

[578 rows x 2 columns]

In [196]:
r2_score(y_train,y_pred)

0.9508582360748522

In [197]:
mean_squared_error(y_train,y_pred)

7254881011.586042

In [199]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_tansformer,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [200]:
scores

[0.6258120445429284,
 0.7104742128874985,
 0.6370351232715723,
 0.7877968443343875,
 0.640505390174119,
 0.5672085626500423,
 0.8135297665643286,
 0.6426634429305914,
 0.4680807389258469,
 0.47419912322156166,
 0.8477068693443552,
 0.8064559062104537,
 0.8372704129790034,
 0.6758437567565004,
 0.7219353642837556,
 0.42446016887086635,
 0.7561297133354187,
 0.8117665178737224,
 0.540326172362986,
 0.6566276523714305,
 0.6185671046251773,
 0.31894664523889715,
 0.5114476790185356,
 0.4043325066820903,
 0.5101416077617628,
 0.4814185246952941,
 0.5491830895196623,
 0.6620352669543476,
 0.5667473617434872,
 0.6612805230645182,
 0.7210599356898411,
 0.6994449493663284,
 0.7181695951098983,
 0.5608764004761002,
 0.34777464729099383,
 0.43379102126181246,
 0.7050043669433897,
 0.45801278288643776,
 0.42744153314155886,
 0.45727258035251195,
 0.5454189271427188,
 0.7313958026427656,
 0.714291069749929,
 0.6563020664932553,
 0.6557211159360916,
 0.4506049301678655,
 0.8023728309492908,
 0.6792449808007223,
 0.38991174530054584,
 0.8096946102661204,
 0.8174679595174738,
 0.7090472519422846,
 0.8392104594375132,
 0.7855813539436677,
 0.6280884482079999,
 0.6746777434739377,
 0.738138304657149,
 0.6509212446070824,
 0.6437289442500882,
 0.7390750963072807,
 0.617757019495292,
 0.5654253730021683,
 0.5185166369487111,
 0.9085439521043092,
 0.48652855151001395,
 0.42992974100490633,
 0.8177022629131641,
 0.674357936234561,
 0.8497230507051847,
 0.7870072298044835,
 0.7429493271884957,
 0.768392129579295,
 0.5761005554392409,
 0.624293119659298,
 0.6481966868191262,
 0.7074832976766041,
 0.5044669812257769,
 0.6824114681784839,
 0.8118223566088155,
 0.7797587792503358,
 0.8850018171250309,
 0.7455916352288482,
 0.6015565653696797,
 0.7866806240818479,
 0.5525789322422888,
 0.5689627014123284,
 0.7317072139556898,
 0.5327961428363674,
 0.5796468932756141,
 0.7425682999647504,
 0.5675842661619439,
 0.5390588832936236,
 0.4625210730451833,
 0.7511925721224484,
 0.5288907109395107,
 0.6471592969557602,
 0.7110710927319632,
 0.7386758951009456,
 0.7619319095208903,
 0.3601559774926891,
 0.6176462379786207,
 0.812938400670419,
 0.5879175113669398,
 0.8371507484780629,
 0.7485935912661703,
 0.5246658685277245,
 0.6964442105899935,
 0.7046807386991039,
 0.6670148955354831,
 0.5710642390782373,
 0.753279915673491,
 0.5039467604305556,
 0.627085278478527,
 0.5673381233755634,
 0.6261688537797173,
 0.7144389770493659,
 0.7525845829124672,
 0.453464913189348,
 0.648657610757274,
 0.4107860050446863,
 0.7399025407817547,
 0.8305555202710955,
 0.5710943972006665,
 0.5326232070761541,
 0.8540425555953715,
 0.5850096821252178,
 0.7266412612063285,
 0.8072843834192374,
 0.8581460952404558,
 0.5613251865428646,
 0.4733517917556017,
 0.6886800956313303,
 0.7834141864526605,
 0.8840169072785553,
 0.788984016821414,
 0.8145292191519495,
 0.3796761945132354,
 0.3844423561232747,
 0.5885311002581394,
 0.8518684669643666,
 0.7030497481740497,
 0.6147420854998249,
 -0.04069261767695709,
 0.5721536943364293,
 0.7806412109665073,
 0.6073472249844709,
 0.38461715025060417,
 0.7379149804352141,
 0.7785437218507836,
 0.6458255238899228,
 0.7598982649107002,
 0.5183118388292963,
 0.2726160500379742,
 0.5780526615409209,
 0.7389475707006019,
 0.650188643375166,
 0.6554089695234815,
 0.6653045845694175,
 0.325271555059619,
 0.8848760529537709,
 0.7154098795333375,
 0.5467043397809557,
 0.5923162764811153,
 0.6817005111503645,
 0.601765610450413,
 0.7159589856688511,
 0.23100724774769466,
 0.43594695655428295,
 0.7484659506535793,
 0.7551099480986241,
 0.7292352109523177,
 0.7366658794819938,
 0.5819521723284573,
 0.6569254861300542,
 0.6387444504932979,
 0.4517536762308104,
 0.6873403582427138,
 0.6015655854749752,
 0.6961323028666322,
 0.579479894916807,
 0.6415280626773119,
 0.4924364183923431,
 0.7646678105695789,
 0.6014364186356611,
 0.3936192788345252,
 0.6624915816190029,
 0.6495698796207379,
 0.6587604263649826,
 0.49256414792702197,
 0.4621482214305568,
 0.8960393717388194,
 0.5937910051975575,
 0.8296580816234707,
 0.790771626329548,
 0.5826470961662293,
 0.4646567456640386,
 0.6067816208189161,
 0.7785132727451989,
 0.6105016880983589,
 0.7042918692142957,
 0.7891003785218621,
 0.7481131896867517,
 0.7022858560654228,
 0.541924530951641,
 0.4961731024736088,
 0.5693537195769396,
 0.4524220033125468,
 0.4876464612458645,
 0.6479889324076027,
 0.5978093656579021,
 0.5435022844691555,
 0.6871718305980725,
 0.7863215899234084,
 0.7212275272404955,
 0.4470389564960585,
 0.4848367222496738,
 0.6586477718850281,
 0.7625569282640028,
 0.6201015263173414,
 0.7846669452500994,
 0.32128030767505,
 0.7996107727429609,
 0.6708554813229902,
 0.711378628840927,
 0.6048684701167537,
 0.7014348488072579,
 0.8078958803060983,
 0.2523254062498289,
 0.6857334466006894,
 0.5029270408202984,
 0.49354105400884274,
 0.5876646665314679,
 0.5517571388222033,
 0.6284382151188048,
 0.7215551405110867,
 0.8116384306561018,
 0.4357668044741019,
 0.42777956622277236,
 0.8399759428866076,
 0.6629815336302158,
 0.6355717151733931,
 0.45189013514595,
 0.42277212711956147,
 0.7961666616862384,
 0.6844905433613993,
 0.7877517165406688,
 0.5165184077215279,
 0.521367787614601,
 0.8810531682368624,
 0.716433285085707,
 0.5021155520219079,
 0.520202890942254,
 0.804650877427922,
 0.84502219718559,
 0.6504974886089678,
 0.4966687256157102,
 0.681954718746212,
 0.7277198432142254,
 0.6350194557928995,
 0.7669478546648208,
 0.6965017922220988,
 0.8042492942180552,
 0.809087514424528,
 0.6359426850869848,
 0.5835408423018975,
 0.5766043015986742,
 0.8093903277860602,
 0.691535019926788,
 0.6774425257856977,
 0.74583934324188,
 0.6831451009436353,
 0.5702943430492933,
 0.6655893498577006,
 0.68942106959723,
 0.7970764071053674,
 0.8211291604967028,
 0.6295560997586949,
 0.7402635974270033,
 0.7178827279973544,
 0.594525936244828,
 0.6863180439911254,
 0.512738139366096,
 0.5943998639651377,
 0.6588303936181119,
 0.7736609075485918,
 0.8479424962088251,
 0.7443346747402542,
 0.4956306356702205,
 0.7785240069160546,
 0.4454487085290554,
 0.6620282438030625,
 0.7206765794719894,
 0.5690949069486215,
 0.8239120971337605,
 0.6403361978519295,
 0.5296180150323417,
 0.5986388978688102,
 0.44301165502481055,
 0.5525811715697224,
 0.7322058020078983,
 0.6855435679486201,
 0.6958474069304676,
 0.5684811435844563,
 0.7613678510013226,
 0.8241672203872716,
 0.6103548574291611,
 0.5362525252203625,
 0.48815084291140187,
 0.5368258291011528,
 0.6996628833696412,
 0.556703639421913,
 0.7875335882200138,
 0.569570108554209,
 0.7723296920946161,
 0.5128638602310374,
 0.6887413326257426,
 0.6426123621851321,
 0.6864267142426888,
 0.5427219144271955,
 0.6643503722109637,
 0.8065557697546426,
 0.71859470092276,
 0.49198186430263735,
 0.8172195370250885,
 0.746955175340636,
 0.5283230894575168,
 0.7072173397300228,
 0.7144584981426085,
 0.7762905562316311,
 0.7609476802424973,
 0.5735943507378316,
 0.688670917458083,
 0.4697019135424687,
 0.7851630714719429,
 0.5981103753721337,
 0.447719249940417,
 0.3422557171205346,
 0.7853124434467004,
 0.7749223161745141,
 0.4156612298457496,
 0.6651045905152861,
 0.4138024720086668,
 0.7491120099695778,
 0.6849048874260373,
 0.6237355048112238,
 0.4914163551588774,
 0.6940409008460442,
 0.7048964345680991,
 0.512927726155326,
 0.6500671320512621,
 0.7290386797149554,
 0.7026003767860073,
 0.6656687663787655,
 0.6795711400759503,
 0.6744985322093775,
 0.7970470975616882,
 0.6898286457000855,
 0.6482881259032321,
 0.7766694069040063,
 0.4823619349758458,
 0.7458273136924097,
 0.632996328257609,
 0.6696451054554736,
 0.8173922190572381,
 0.7071084536258423,
 0.2882857148948603,
 0.5634720001470234,
 0.7394135278033191,
 0.7483766914047272,
 0.41571436201379075,
 0.7110895081236766,
 0.7913978098480151,
 0.7417500360467852,
 0.7440200964729409,
 0.7006867927694311,
 0.6967101796730932,
 0.7447714717792218,
 0.5199779239723429,
 0.7286465763056014,
 0.6424191232217626,
 0.6055283492471335,
 0.6410311926933997,
 0.3782918854320677,
 0.6604454658720729,
 0.5496480128455153,
 0.5207226591259251,
 0.7817098328688434,
 0.5826585979538541,
 0.31958656295450716,
 0.5616495445325969,
 0.4025373092445179,
 0.8615656256625088,
 0.6034435039993273,
 0.7396523322630311,
 0.8209830992295482,
 0.4902588163784578,
 0.6305169067405194,
 0.8244937494363396,
 0.5432441284268096,
 0.794211246762604,
 0.7804386913265133,
 0.5286979631419322,
 0.5526305065630521,
 0.7731605536647113,
 0.7463388663790484,
 0.7431092074518346,
 0.6284133282071427,
 0.7892633905644046,
 0.7403817888412935,
 0.6652836437579641,
 0.7321616498445462,
 0.49801153293939315,
 0.4077750275634263,
 0.7767664430246348,
 0.6427459921951367,
 0.8154320703118659,
 0.5585728740424203,
 0.7611370433748985,
 0.8377295552844013,
 0.7670682416573502,
 0.6130547922906566,
 0.799412122586792,
 0.4475335455826156,
 0.7664781685799124,
 0.7827573387792015,
 0.7097664084958031,
 0.6958094353098434,
 0.7743827942533981,
 0.4704592683671911,
 0.4129994350194718,
 0.8072520779013457,
 0.7167714185510456,
 0.5931895503938057,
 0.5904378721665093,
 0.8018978619927856,
 0.623662142340698,
 0.3770365813433687,
 0.6501325970951327,
 0.8615685540507861,
 0.5486716360626323,
 0.6728952685408638,
 0.33760970053494765,
 0.7642072267481026,
 0.8128809559031218,
 0.22987859420185597,
 0.5981940723558671,
 0.43627244941963916,
 0.7513274411880634,
 0.7882656691867772,
 0.8345071903719518,
 0.7839738169224268,
 0.7042761640832828,
 0.6488203541049427,
 0.7183874965347066,
 0.6650651063466626,
 0.44909084571379176,
 0.4399413343602606,
 0.5363472952992234,
 0.6805760621040515,
 0.654896390474199,
 0.6036480856039339,
 0.567355059031415,
 0.3271678299243711,
 0.5673452123518452,
 0.5444485755015556,
 0.7762212663791346,
 0.8357684053555995,
 0.6320015602108127,
 0.6938330575076482,
 0.789250878865074,
 0.6521487871798165,
 0.6365034700672016,
 0.7089367026393764,
 0.7467374677683153,
 0.6800445403713922,
 0.7073776884194429,
 0.5247625142573065,
 0.8079057194729539,
 0.5245760470143508,
 0.6598770342195943,
 0.7241415714536017,
 0.6782242781060122,
 0.7670185642944155,
 0.589939936677988,
 0.4635558538891986,
 0.471325650788848,
 0.5573658866355259,
 0.5104996682780344,
 0.7898777982768888,
 0.24620347032782597,
 0.591919374561275,
 0.6763902401940957,
 0.2888733621483156,
 0.5557634791593502,
 0.6706733320156275,
 0.7301626317214949,
 0.4629762248327618,
 0.357004161949269,
 0.695618916240188,
 0.6951594666117299,
 0.7438446636076781,
 0.7481114486502343,
 0.824914214516615,
 0.5484927372855346,
 0.5600495492735944,
 0.7377342120100804,
 0.7806056158170219,
 0.42984509999164466,
 0.6249281053530575,
 0.8420699360115507,
 0.6647671410985698,
 0.7535183525762976,
 0.47705234118452544,
 0.7304230821737148,
 0.7332291646077842,
 0.5809378871529223,
 0.3872122650546209,
 0.5632289332775632,
 0.7007146324463787,
 0.8445162933303,
 0.6053130421292068,
 0.6896891792607631,
 0.6128341980068291,
 0.5877331642811361,
 0.7284024484139999,
 0.7135307574336661,
 0.5849532567522107,
 0.6708299146018092,
 0.4013724106272537,
 0.7600824327794323,
 0.7811890920611047,
 0.628901198996163,
 0.6897967687192865,
 0.7419490390024279,
 0.4650338851400768,
 0.8544001466651682,
 0.8328122685659236,
 0.6420496277612657,
 0.7049419006603108,
 0.548098852129463,
 0.7368505474312552,
 0.6139982756500099,
 0.6711859107330027,
 0.3994362252018583,
 0.5188211646732707,
 0.7865181056018974,
 0.6680857230687758,
 0.9296506291489193,
 0.5555542741043416,
 0.545569075318872,
 0.42797969382281253,
 0.7422051278999624,
 0.8039874894107878,
 0.7699809997345071,
 0.528691900656607,
 0.7478903246856978,
 0.8318577125332457,
 0.548795473633086,
 0.7909864362426866,
 0.44863209405132387,
 0.7898057501520842,
 0.7079628575567369,
 0.7077277408107367,
 0.49497399628306016,
 0.6387726807221648,
 0.8719452613924459,
 0.5533888715399242,
 0.6812566518584713,
 0.6058834768009437,
 0.8091752202235537,
 0.7904439992737133,
 0.6488428354545268,
 0.698017759523623,
 0.7976609453073824,
 0.5468398422418466,
 0.6957928555849219,
 0.645315399544907,
 0.6654800511563244,
 0.7887577064744129,
 0.7846784409582657,
 0.6177452272231729,
 0.7187325815133287,
 0.8423043174396894,
 0.7209964182797104,
 0.6076580470566761,
 0.7791639774877298,
 0.6385456455837915,
 0.5348038519619784,
 0.739689286850344,
 0.6427659306556013,
 0.5912179431702267,
 0.6756434192576071,
 0.49238137763216216,
 0.4984507628241689,
 0.7904435173333938,
 0.7866935505129968,
 0.6779792418891206,
 0.6501217928227683,
 0.7577982970606333,
 0.7979335164156323,
 0.7540092833926787,
 0.3165888385924276,
 0.7534624011418494,
 0.6986153326976923,
 0.5379986373636634,
 0.44678714146992615,
 0.29167871341221163,
 0.3977982334770267,
 0.63140977441762,
 0.4815048077988391,
 0.7284842125402013,
 0.44307110998735244,
 0.6819852724340161,
 0.8664738231968415,
 0.6744756250309509,
 0.4626377914190436,
 0.043084879471313675,
 0.6943726585435653,
 0.7624169967146273,
 0.8110030504508682,
 0.8155895658648017,
 0.4985639166954067,
 0.841181681950051,
 0.8589109603731293,
 0.5955330633642836,
 0.8284173734793967,
 0.756254960724312,
 0.6335015206702386,
 0.6604928880404594,
 0.7822058434315788,
 0.6991801475259816,
 0.6828751073132419,
 0.7462004017715564,
 0.6531296914859716,
 0.7425412590396023,
 0.6064552165812669,
 0.6423326130041194,
 0.5294528868931512,
 0.6026824847676231,
 0.8468521743857238,
 0.727927425851087,
 0.5560297145486235,
 0.676405310613232,
 0.8208435274588889,
 0.7399775088323534,
 0.7216822011987114,
 0.8007345420273736,
 0.585606881170255,
 0.5590586253432066,
 0.8590352525083498,
 0.593999679454313,
 0.25562223695116204,
 0.7933434084975866,
 0.7994242677612895,
 0.4367041007195185,
 0.6622438062244284,
 0.6708855787717503,
 0.5308905622395614,
 0.47320065592498095,
 0.714087467355669,
 0.5980066623729949,
 0.6948130545336504,
 0.5136138502225085,
 0.6232917077875852,
 0.8214888208007749,
 0.6168750456317376,
 0.6826181869855983,
 0.6076826176183014,
 0.20366530569476782,
 0.5534667747812421,
 0.6643429396644178,
 0.5707022742133694,
 0.8073420665199158,
 0.7140271442328695,
 0.5819331565261369,
 0.7403993266454869,
 -0.29025142414346505,
 0.48370093123760494,
 0.6452200459588452,
 0.8055796722315818,
 0.6994524704507007,
 0.5931973138064661,
 0.7259271765453713,
 0.8614627189432135,
 0.42900674683408924,
 0.7280538220477033,
 0.6988645609343789,
 0.4428600956474925,
 0.6181783505922165,
 0.7211737166877499,
 0.684683641196123,
 0.5552132457273706,
 0.7480826507516778,
 0.7706823395211985,
 0.6589901414592019,
 0.5883784047738683,
 0.45225883701880343,
 0.7104512229958462,
 0.7355452283411277,
 0.735523636640629,
 0.7584700033145034,
 0.7112979078542307,
 0.46972111402767447,
 0.7429764202702809,
 0.744173878461367,
 0.5992322456328378,
 0.6534938440044924,
 0.6735254192039295,
 0.6890474922388573,
 0.6828964532626451,
 0.7071499695220596,
 0.744815242350849,
 0.3655048895230776,
 0.7214806358183148,
 0.6594618674627747,
 0.6218538869516488,
 0.736992286906051,
 0.6562687234573297,
 0.46792281136398617,
 0.7082423954706891,
 0.5536620206715062,
 0.7102671180529563,
 0.6999449791882488,
 0.8227541849043741,
 0.6438788966696884,
 0.6488221925600318,
 0.5644753034757715,
 0.7240406439761539,
 0.7329260270704934,
 0.8241142968563985,
 0.7540893167802463,
 0.4949271640945673,
 0.45434863422518135,
 0.7595217351769137,
 0.4095440995087388,
 0.7624059587512811,
 0.733277350423964,
 0.8605850533675072,
 0.6957564201551626,
 0.8344064918663233,
 0.8819218665055774,
 0.6628121317658378,
 0.6583728957413484,
 0.7414248630280221,
 0.6886735137140074,
 0.592046429676143,
 0.7232410847672726,
 0.42208176291646604,
 0.7319297366143827,
 0.7187426961242125,
 0.8709372347806514,
 0.7310903384704857,
 0.6378648676009264,
 0.7418022457169495,
 0.5573521034528748,
 0.8463168670468373,
 0.8225867864436807,
 0.7660653955446516,
 0.6026103923865098,
 0.7952696949198669,
 0.63364897352435,
 0.7917700479418407,
 0.5133601344310877,
 0.49656534772515915,
 0.7724451685860038,
 0.296857752237504,
 0.6836886701903517,
 0.5647296477700614,
 0.7889602932114665,
 0.6576847777705352,
 0.7690491012409825,
 0.8011183828590892,
 0.5383202325497871,
 0.4141721455890859,
 0.6809585318917776,
 0.637567881662084,
 0.5703499281758588,
 0.7604372094326607,
 0.5294675148060793,
 0.5170267061201053,
 0.7231044427309885,
 0.4030050826818731,
 0.5082175952411445,
 0.7302497225724167,
 0.8080206763471174,
 0.6527395487765228,
 0.4836217129620213,
 0.812216237863246,
 0.6650675458374959,
 0.5473705915084539,
 0.7611613362581842,
 0.6612263486992953,
 0.6956313515814057,
 0.7589911993243073,
 0.5292407194837483,
 0.7912089957123076,
 0.6191550049720204,
 0.6466317485588695,
 0.6438622479321641,
 0.8246346023488699,
 0.6092476424822467,
 0.6386684292684186,
 0.752611426329437,
 0.6788598915117215,
 0.8571923319386168,
 0.8664234856177686,
 0.2868469340288261,
 0.48295696253254194,
 0.5886585660535388,
 0.642610933529461,
 0.5147941062012014,
 0.6153649234219709,
 0.702566470489791,
 0.830088454310795,
 0.8078715347642245,
 0.4960842695703671,
 0.34536799297397536,
 0.6015107984450141,
 0.36441574591814074,
 0.7104813061428379,
 0.7957518058182986,
 0.8404449761244643,
 0.6520693657054165,
 0.5362967427334753,
 0.5690700468802379,
 0.8439395921437924,
 0.5244478608687211,
 0.8614853160607686,
 0.5275196007708709,
 0.3977923124457632,
 0.39815051176035965,
 0.865843735543992,
 0.7717384005650625,
 0.8678186767927762,
 0.6899667368599117,
 0.5261769461728196,
 0.5221629502549936,
 0.8054675417521657,
 0.6504706354597506,
 0.3838056799098206,
 0.6874589830266229,
 0.388589033871901,
 0.7125784570075528,
 0.5937299890397465,
 0.7355066723462218,
 0.8608558030400233,
 0.6313646976067501,
 0.9047574145501842,
 0.4180302963799637,
 0.4156707003080554,
 0.6370302364207914,
 0.7436978103038203,
 0.5146968357524853,
 0.6101812367977362,
 0.6319068961046133,
 0.7002220245587358,
 0.28526971859807493,
 0.6622320000165701,
 0.7804605162092808,
 0.726395609540534,
 0.6544335858267671,
 0.5919022348813457,
 0.821252983275434,
 0.728074377928265,
 0.7722392657777666,
 0.4436316217351667,
 0.6800506308304242,
 0.6472111186937681,
 0.7430343861475768,
 0.7587181379597998,
 0.6447218505395567,
 0.6005974328056309,
 0.377501485909416,
 0.7816011944408578,
 0.5913940037768642,
 0.7960660800846,
 0.5480058949414994,
 0.690042897914503,
 0.5880552494699336,
 0.6648123423859557,
 0.6586968616649407,
 0.6376998243126348,
 0.5809916592474771,
 0.7157375038021591,
 0.8147298504027487,
 0.7863883571039321,
 0.6522739340545957,
 0.8223639477076936,
 0.6039385308415814,
 0.7092184227563583,
 0.6776738352219331,
 0.5115123214254302,
 0.8132098685874682,
 0.9431863778095909,
 0.6887884797348703,
 0.8302483370665169,
 0.8498362564458555,
 0.6166917484574344,
 0.5240450870173419,
 0.6958214754271828,
 0.7250177206946662,
 0.6100339083268635,
 0.6592053710481784,
 0.7373948774093014,
 0.6630498513506287,
 0.817364496411522,
 0.7846887357461033,
 0.46757634339320975,
 0.6662270301252994,
 0.41076185811887167,
 0.7808931169664494,
 0.6482487337889498,
 0.4324927707308045,
 0.7302024668566063,
 0.6287985507803813,
 0.5158441428831735,
 0.7301274028194953,
 0.810229360935308,
 0.7851179661791864,
 0.793266072897455,
 0.6459618787673503,
 0.6843703948440119,
 0.7566499407476321,
 0.7478722440237213,
 0.6428531468700813,
 0.6782238000129885,
 0.6367601104055349,
 0.5727128869615719,
 0.6706208015414736,
 0.6576761930485776,
 0.614796665818448,
 0.6773670824645608,
 0.6977589639225732,
 0.8980386413689517,
 0.619991916691667,
 0.7205150408324784,
 0.6624344946048897,
 0.7339265881135428,
 0.7820355474070925,
 0.8455989505007768,
 0.7671069801236414,
 0.7449874564987318,
 0.44654767573404186,
 0.7364372260547841,
 0.7435641312166452,
 0.5402829593275421,
 0.4686120942766543,
 0.7447938613077305,
 0.8275986836529291,
 0.615062507158305,
 0.8905998293534726,
 0.5464050382564294,
 0.7893277947221371,
 0.8712868355044654,

In [202]:
np.argmax(scores)

893

In [207]:
record= pd.DataFrame(columns=X_test.columns ,data= np.array(['Toyota Corolla Altis','Toyota',20090101,132000,'Petrol']).reshape(1,5))

In [213]:
pipe.predict(record)

array([289304.75499488])

In [215]:
record= pd.DataFrame(columns=X_test.columns ,data= np.array(['Ford EcoSport Titanium','Ford',20140101,36000,'Diesel']).reshape(1,5))

In [216]:
pipe.predict(record)

array([560269.11392543])